/*В базе данных MS SQL Server есть продукты и категории. 
Одному продукту может соответствовать много категорий, в одной категории может быть много продуктов. 
Напишите SQL запрос для выбора всех пар «Имя продукта – Имя категории». 
Если у продукта нет категорий, то его имя все равно должно выводиться.*/
CREATE TABLE [dbo].[PRODUCTS] (
[ID] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
[NAME] nvarchar(max) NOT NULL
);

INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ШКАФ');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('СТОЛ');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('СТУЛ');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ЧАСЫ');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ФЕН');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ПЛЕД');

CREATE TABLE [dbo].[CATEGORIES] (
[ID] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
[NAME] nvarchar(max) NOT NULL
);

INSERT INTO [dbo].CATEGORIES ([NAME]) VALUES ('ДОМ');
INSERT INTO [dbo].CATEGORIES ([NAME]) VALUES ('УЮТ');
INSERT INTO [dbo].CATEGORIES ([NAME]) VALUES ('БЫТ');

CREATE TABLE [dbo].[PRODUCTSCATEGORIES] (
[PRODUCTID] INT FOREIGN KEY REFERENCES [dbo].[PRODUCTS] ([ID]),
[CATEGORYID] INT FOREIGN KEY REFERENCES [dbo].[CATEGORIES]([ID])
);

INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (1,2);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (1,1);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (1,3);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (2,3);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (2,2);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (3,1);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (3,2);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (4,1);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (4,3);


SELECT PRODUCTS.NAME AS "ИМЯ ТОВАРА", CATEGORIES.NAME AS "ИМЯ КАТЕГОРИИ" FROM PRODUCTS
LEFT JOIN [dbo].PRODUCTSCATEGORIES ON (PRODUCTS.ID = PRODUCTSCATEGORIES.PRODUCTID )
lEFT JOIN [dbo].CATEGORIES ON (PRODUCTSCATEGORIES.CATEGORYID = CATEGORIES.ID );
