
CREATE TABLE [dbo].[PRODUCTS] (
[ID] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
[NAME] nvarchar(max) NOT NULL
);

INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ØÊÀÔ');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ÑÒÎË');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ÑÒÓË');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('×ÀÑÛ');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ÔÅÍ');
INSERT INTO [dbo].PRODUCTS ([NAME]) VALUES ('ÏËÅÄ');

CREATE TABLE [dbo].[CATEGORIES] (
[ID] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
[NAME] nvarchar(max) NOT NULL
);

INSERT INTO [dbo].CATEGORIES ([NAME]) VALUES ('ÄÎÌ');
INSERT INTO [dbo].CATEGORIES ([NAME]) VALUES ('ÓÞÒ');
INSERT INTO [dbo].CATEGORIES ([NAME]) VALUES ('ÁÛÒ');

CREATE TABLE [dbo].[PRODUCTSCATEGORIES] (
[PRODUCTID] INT FOREIGN KEY REFERENCES [dbo].[PRODUCTS] ([ID]),
[CATEGORYID] INT FOREIGN KEY REFERENCES [dbo].[CATEGORIES]([ID])
);

INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (1,2);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (1,1);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (1,3);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (2,3);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (2,2);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (3,1);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (3,2);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (4,1);
INSERT INTO PRODUCTSCATEGORIES ([PRODUCTID],[CATEGORYID]) VALUES (4,3);


SELECT PRODUCTS.NAME AS "ÈÌß ÒÎÂÀÐÀ", CATEGORIES.NAME AS "ÈÌß ÊÀÒÅÃÎÐÈÈ" FROM PRODUCTS
LEFT JOIN [dbo].PRODUCTSCATEGORIES ON (PRODUCTS.ID = PRODUCTSCATEGORIES.PRODUCTID )
lEFT JOIN [dbo].CATEGORIES ON (PRODUCTSCATEGORIES.CATEGORYID = CATEGORIES.ID );
